version: '3.9'

services: 
  db:
    image: postgres
    container_name: mp_jcwd0510_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - '6543:5432'
    networks:
      - express-network

networks:
  express-network: